# ---------------------------------------------------------
# CE topology / scaling
# ---------------------------------------------------------

variable "ce_count" {
  description = "Number of single-node Secure Mesh v2 CE sites (1..3). Each originates the LB VIP via eBGP to the Azure Route Server for active/active ECMP."
  type        = number
  default     = 3

  validation {
    condition     = var.ce_count >= 1 && var.ce_count <= 3
    error_message = "ce_count must be between 1 and 3."
  }
}

variable "region_short" {
  description = "Short region token used to build the per-CE key and site name (component `mcn-ce-ha` + region `eastus` -> site `mcn-ce-ha-eastus01`). Leave null (the default) to use var.location verbatim; set it only when the Azure region name is longer than you want inside object names."
  type        = string
  default     = null
}

variable "site_prefix" {
  description = "Prefix for XC site names (site = <prefix>-<region_short>0<n>). Leave null (the default) to use var.component, which is what keeps every object name descending from one value. Set it only to hold existing site names steady: renaming a site replaces the CE VM, because the site name is the ClusterName baked into cloud-init and cloud-init only runs on first boot."
  type        = string
  default     = null
}

variable "ce_asn" {
  description = "BGP ASN for the Customer Edge nodes (eBGP local ASN)."
  type        = number
  default     = 64512
}

variable "rs_asn" {
  description = "BGP ASN of the Azure Route Server (fixed by Azure at 65515)."
  type        = number
  default     = 65515
}

variable "enable_bgp" {
  description = "Create the per-CE xcsh_bgp objects. Defaults true — BGP/ECMP is the point of this deployment — and nothing gates it: the object-ref name length blocker that once forced it false was removed in provider v3.74.0. Retained only as an escape hatch for planning or deploying the topology without BGP."
  type        = bool
  default     = true
}

variable "approve_registration" {
  description = "Approve each CE's runtime registration from Terraform (the xcsh_site_registration data source resolves the r-<uuid> registration name from the site name, and xcsh_registration_approval approves it). Two-phase by nature: the registration only exists after the CE has booted and registered, so the first apply plans no approval and a later apply creates it. Set false to leave approval to an operator."
  type        = bool
  default     = true
}

# ---------------------------------------------------------
# Site registration token (optional override)
# ---------------------------------------------------------
# The CE VM cloud-init consumes a tenant-scoped, reusable site registration
# token (ClusterName + Token). The token is now provider-generated by the
# xcsh_token.ce resource (its Computed uid); this var is an optional override.
variable "registration_token" {
  description = "Optional override for the CE cloud-init site registration token. When empty (the default) the provider-generated xcsh_token.ce.uid is used; set a non-empty value to inject an externally-minted token instead."
  type        = string
  default     = ""
  sensitive   = true
}

variable "ce_os_version" {
  description = "CE OS version, set at CREATE time (e.g. 9.2026.14). EMPTY IS NOT NEUTRAL: at create the server fills an empty field with the newest ADVERTISED version and installs it, so an empty value makes the result depend on the date rather than on this configuration — pin it deliberately (#714, #726). Terraform cannot change it afterwards: the update is rejected 400 in every direction, including un-pinning. The platform CAN change it in place via POST /api/config/namespaces/{ns}/sites/{name}/upgrade_os, so a version change is not a rebuild — but the provider cannot drive that yet (xcsh#1390), and using it leaves this value disagreeing with the live site."
  type        = string

  validation {
    condition     = var.ce_os_version != ""
    error_message = "ce_os_version cannot be empty. Empty is not neutral: at create time F5 XC fills an empty field with the newest advertised version, making installed versions depend on the date of apply rather than on this configuration. Pin a version explicitly (e.g. ce_os_version = \"9.2024.6\")."
  }
}

variable "ce_sw_version" {
  description = "CE F5XC software version, set at CREATE time (e.g. crt-20260201-0179). The node installs this on first boot; it chooses the destination, not whether an install happens. Do not assume the image ships something older — image 0.9.2 ships a NEWER build than this fleet pins, and a backwards pin is routine (#714, #726). EMPTY IS NOT NEUTRAL: the server fills an empty field with the newest ADVERTISED version and installs it, which on the image default disk is the combination measured to FAIL — pin it deliberately, and see modules/ce-node for the disk. Terraform cannot change it afterwards (update rejected 400 in every direction), but the platform can in place via POST /api/config/namespaces/{ns}/sites/{name}/upgrade_sw (xcsh#1390)."
  type        = string

  validation {
    condition     = var.ce_sw_version != ""
    error_message = "ce_sw_version cannot be empty. Empty is not neutral: at create time F5 XC fills an empty field with the newest advertised version, making installed versions depend on the date of apply rather than on this configuration. Pin a version explicitly (e.g. ce_sw_version = \"crt-20250613-3382\")."
  }
}
