frr version 10.0
frr defaults traditional
hostname local-tor-router
log syslog informational
service integrated-vtysh-config
!
no bgp ebgp-requires-policy
!
router bgp 65515
 bgp router-id 10.100.0.1
 no bgp default ipv4-unicast
 maximum-paths 4
 !
 neighbor CE_CLUSTER peer-group
 neighbor CE_CLUSTER remote-as 64512
 neighbor 10.100.0.11 peer-group CE_CLUSTER
 neighbor 10.100.0.12 peer-group CE_CLUSTER
 neighbor 10.100.0.13 peer-group CE_CLUSTER
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor CE_CLUSTER activate
 exit-address-family
!
